# Generated by Django 3.2.4 on 2022-04-16 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParamToCategorySettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.parameter')),
            ],
            options={
                'unique_together': {('parameter', 'category')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(related_name='categories', through='categories.ParamToCategorySettings', to='parameters.Parameter'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Родительская категория'),
        ),
    ]
