# Generated by Django 3.2.4 on 2022-03-16 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamToCategorySettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('param_uuid', models.UUIDField()),
                ('category_uuid', models.UUIDField()),
                ('required', models.BooleanField()),
            ],
            options={
                'unique_together': {('param_uuid', 'category_uuid')},
            },
        ),
    ]
