# Generated by Django 3.2.4 on 2022-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParamToCategorySettings',
            new_name='CategoryParametersSettings',
        ),
    ]
