# Generated by Django 3.2.4 on 2021-09-12 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measurement_group',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('multiplier', models.IntegerField()),
                ('min_value', models.BigIntegerField()),
                ('min_is_included', models.BooleanField(default=True)),
                ('max_value', models.BigIntegerField()),
                ('max_is_included', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='measurements.measurementgroup')),
            ],
            options={
                'db_table': 'measurement_unit',
            },
        ),
    ]
