# Generated by Django 3.2.4 on 2021-12-01 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementGroupForParameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('measurement_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='measurements.measurementgroup')),
            ],
            options={
                'db_table': 'measurement_group_x_parameter',
                'unique_together': {('parameter_name', 'model_name')},
            },
        ),
    ]
