# Generated by Django 3.2.4 on 2022-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='max_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='min_value',
            field=models.FloatField(),
        ),
    ]
