# Generated by Django 3.2.4 on 2022-04-22 07:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericParameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_parameters', to='parameters.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ListParameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, null=True, size=None)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_parameters', to='parameters.parameter')),
            ],
        ),
    ]
