# Generated by Django 3.2.4 on 2022-05-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initial'),
        ('parameters', '0002_listparameter_numericparameter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listparameter',
            unique_together={('parameter', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='numericparameter',
            unique_together={('parameter', 'component')},
        ),
    ]
