# Generated by Django 3.2.4 on 2021-07-10 16:06

from django.db import migrations
from django.db import connection

from asonika_ecb.settings import BASE_COMPONENT_MODEL_NAME


def create_base_component_table(apps, schema_editor):
    CREATE_UUID_EXTENSION_QUERY = 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
    CREATE_TABLE_QUERY = (
        f'CREATE TABLE {BASE_COMPONENT_MODEL_NAME}'
        f'(uuid uuid DEFAULT uuid_generate_v4 (), PRIMARY KEY (uuid));'
    )

    with connection.cursor() as cursor:
        cursor.execute(CREATE_UUID_EXTENSION_QUERY)
        cursor.execute(CREATE_TABLE_QUERY)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            create_base_component_table, migrations.RunPython.noop
        ),
    ]
