# Generated by Django 3.2.4 on 2022-04-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0002_listparameter_numericparameter'),
        ('components', '0001_initial'),
        ('specifications', '0002_make_name_field_unique'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='list_parameters',
            field=models.ManyToManyField(related_name='components_with_list_params', through='parameters.ListParameter', to='parameters.Parameter'),
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturers.manufacturer'),
        ),
        migrations.AddField(
            model_name='component',
            name='numeric_parameters',
            field=models.ManyToManyField(related_name='components_with_numeric_params', through='parameters.NumericParameter', to='parameters.Parameter'),
        ),
        migrations.AddField(
            model_name='component',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='specifications.specification'),
        ),
    ]
